In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib 

In [46]:
df=pd.read_csv('housing_prices.csv')
df.head()

AREA  FLOOR  ROOM CODE  PRICE
0  1000      7     2    B   5618
1  1030      7     1    A   5201
2  1060      1     1    A   4779
3  1090      6     1    A   5425
4  1120      0     2    B   5657

In [47]:
df=df.iloc[:,[0,1,2,4]]
x=df.iloc[:,:3].values
y=df.iloc[:,3].values
print(x[:5])
print(y[:5])

[[1000    7    2]
 [1030    7    1]
 [1060    1    1]
 [1090    6    1]
 [1120    0    2]]
[5618 5201 4779 5425 5657]


In [48]:
#splitting datasets
from sklearn.model_selection import train_test_split


In [49]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=100)
print(x_train.shape)
print(x_test.shape)
print(x_train.shape)
print(x_test.shape)

(40, 3)
(10, 3)
(40, 3)
(10, 3)


In [50]:
from sklearn.linear_model import LinearRegression
mlr_model= LinearRegression(fit_intercept=True)
mlr_model.fit(x_train,y_train)

LinearRegression()

In [51]:
print(mlr_model.intercept_) # (PRICE=(-4481.80028058845)+8.65903854)*AREA
print(mlr_model.coef_)#y=c+mx

-3106.4127920034116
[   4.68576316   71.78274093 1894.45529322]


In [52]:
print(mlr_model.score(x_train,y_train))
print(mlr_model.score(x_test,y_test))

0.9646204930750824
0.8606154687481633
